//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoArtigos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_artigos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_artigos()
        {
            this.tb_necessidades = new HashSet<tb_necessidades>();
        }
    
        public int codigo { get; set; }
        public string referencia { get; set; }
        public string descricao { get; set; }
        public System.DateTime data_criado { get; set; }
        public System.DateTime data_alterado { get; set; }
        public int codigo_utilizador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_necessidades> tb_necessidades { get; set; }
    }
}
