//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoArtigos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_artigos
    {
        [Required]
        public int codigo { get; set; }

        [Required(ErrorMessage = "Introduza a referência do artigo!")]
        [RegularExpression(@"^[a-zA-Z0-9]+$", ErrorMessage = "Insira apenas caracteres alfanúmericos!")]
        [StringLength(11, ErrorMessage = "A referência deve ter um máximo de {1} caracteres")]
        public string referencia { get; set; }

        [Required(ErrorMessage = "Introduza uma descrição para o artigo!")]
        [StringLength(30, ErrorMessage = "A descrição deve ter entre {2} a {1} caracteres", MinimumLength = 5)]
        public string descricao { get; set; }
        
        [Required]
        public DateTime data_criado { get; set; }
        
        [Required]
        public DateTime data_alterado { get; set; }

        [Required(ErrorMessage = "Introduza o seu número de utilizador!")]
        [Display(Name = "Número de utilizador")]
        [Range(1, 99999999999, ErrorMessage = "{0} deve estar contido entre {1} e {2}.")]
        public int codigo_utilizador { get; set; }
    }
}
