//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoArtigos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_artigos
    {
        [Required]
        public int codigo { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z0-9]+$", ErrorMessage = "Insira apenas caracteres alfanúmericos!")]
        public string referencia { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "A descrição deve ter entre {2} a {1} caracteres", MinimumLength = 5)]
        public string descricao { get; set; }
        
        [Required]
        public DateTime data_criado { get; set; }
        
        [Required]
        public DateTime data_alterado { get; set; }

        [Required]
        [RegularExpression(@"^[1-9]\d*$", ErrorMessage = "Insira o seu número de utilizador!")]
        public int codigo_utilizador { get; set; }
    }
}
