//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoArtigos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_utilizadores
    {
        public long codigo { get; set; }
        public string utilizador { get; set; }
        public string password { get; set; }
        public string nome { get; set; }
        public System.DateTime data_criacao { get; set; }
        public System.DateTime data_ultimo_acesso { get; set; }
        public string bloqueado { get; set; }
        public short numero_tentativas { get; set; }
    }
}
